### ISSUE TITLE
Captcha Solving algorithm

### ISSUE THREAD

**Issue by abhishek72850** [profhacker3/CoWin-Termux#1]
Your program is super awesome, i wanted to ask if i can use your captcha solving code in my appointment scheduler, and also is there any edge case where this might fail?

**Comment by profhacker3** [comment]
Thanks for A2A,

It doesn't not solve Captcha, as 45+ users don't require Captcha to book slot.

I am not the creator/owner of this repo. Here is the link of the main project.

https://github.com/truroshan/CoWin-Termux.git
